#!/usr/bin/env ruby

RESET   = "\033[0m"
RED     = "\033[31m"
GREEN   = "\033[32m"
YELLOW  = "\033[33m"
BLUE    = "\033[34m"

puts "macinstall version 0.1"
puts RED + "⚠️ Please back up your system before using this script." + RESET
sleep 2

if (ARGV.length < 2)
  puts "Usage: mac-install name email"
  abort
end

USER_NAME = ARGV[0]
USER_MAIL = ARGV[1]

COMMANDS = {
  "Software Updates" => "sudo softwareupdate -ia",
  "XCode tools" => "xcode-select --install",
  "Homebrew" => "ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\" && echo 'export PATH=\"/usr/local/bin:$PATH\"' >> ~/.bash_profile && brew doctor",
  "Git" => "brew install git \
  && git config --global user.name \"#{USER_NAME}\" \
  && git config --global user.email \"#{USER_MAIL}\"\
  && git config --global credential.helper osxkeychain",
  "iTerm2" => "brew cask install iterm2",
  "Nax's dotfiles fork" => "git clone https://github.com/aurelien-ldp/dotfiles.git ~/.dotfiles \
  && ~/.dotfiles/bin/dotfiles install -a",
  "Google Chrome" => "brew cask install google-chrome",
  "Neovim" => "brew install neovim/neovim/neovim",
  "RVM" => "curl -L https://get.rvm.io | bash -s stable --ruby",
  "GPG Suite" => "brew cask install gpgtools",
  "Atom" => "brew cask install atom",
  "Transmission" => "brew cask install transmission",
  "⚠️ WARNING - MacOS configuration derived from: https://github.com/mathiasbynens/dotfiles/blob/master/.macos\
  ⚠ Can modify a lot of settings, please review it before using it.\
  You can execute it after by running the command above." => "sh macos-config",
  "Reboot" => "sudo shutdown -r now",
}

def ok?(command)
  puts "Command: " + command
  print "Is that ok? [Yn] "
  ok = $stdin.gets
  return ok =~ /^[Yy]$|^$/
end

def install_command(command)
  if (ok? command)
    print YELLOW
    system command
    print RESET
  else
    puts "Skipping..."
  end
end

COMMANDS.each do |k, v|
  puts
  puts BLUE + k + RESET
  k.length.times do print "-" end
  puts ; puts
  install_command v
end
